INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '003', 'Banco da Amazônia');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '004', 'Banco do Nordeste');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '021', 'Banestes');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '025', 'Banco Alfa');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '027', 'Besc');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '029', 'Banerj');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '031', 'Banco Beg');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '033', 'Banco Santander Banespa');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '036', 'Banco Bem');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '037', 'Banpará');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '038', 'Banestado');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '039', 'BEP');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '040', 'Banco Cargill');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '041', 'Banrisul');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '044', 'BVA');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '045', 'Banco Opportunity');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '047', 'Banese');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '062', 'Hipercard');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '063', 'Ibibank');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '065', 'Lemon Bank');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '066', 'Banco Morgan Stanley Dean Witter');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '069', 'BPN Brasil');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '070', 'Banco de Brasília – BRB');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '072', 'Banco Rural');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '073', 'Banco Popular');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '074', 'Banco J. Safra');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '075', 'Banco CR2');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '076', 'Banco KDB');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '096', 'Banco BMF');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '104', 'Caixa Econômica Federal');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '107', 'Banco BBM');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '116', 'Banco Único');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '151', 'Nossa Caixa');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '175', 'Banco Finasa');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '184', 'Banco Itaú BBA');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '204', 'American Express Bank');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '208', 'Banco Pactual');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '212', 'Banco Matone');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '213', 'Banco Arbi');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '214', 'Banco Dibens');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '217', 'Banco Joh Deere');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '218', 'Banco Bonsucesso');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '222', 'Banco Calyon Brasil');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '224', 'Banco Fibra');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '225', 'Banco Brascan');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '229', 'Banco Cruzeiro');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '230', 'Unicard');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '233', 'Banco GE Capital');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '237', 'Bradesco');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '241', 'Banco Clássico');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '243', 'Banco Stock Máxima');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '246', 'Banco ABC Brasil');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '248', 'Banco Boavista Interatlântico');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '249', 'Investcred Unibanco');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '250', 'Banco Schahin');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '252', 'Fininvest');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '254', 'Paraná Banco');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '263', 'Banco Cacique');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '265', 'Banco Fator');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '266', 'Banco Cédula');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '300', 'Banco de la Nación Argentina');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '318', 'Banco BMG');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '320', 'Banco Industrial e Comercial');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '356', 'ABN Amro Real');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '341', 'Itau');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '347', 'Sudameris');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '351', 'Banco Santander');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '353', 'Banco Santander Brasil');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '366', 'Banco Societe Generale Brasil');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '370', 'Banco WestLB');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '376', 'JP Morgan');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '389', 'Banco Mercantil do Brasil');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '394', 'Banco Mercantil de Crédito');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '399', 'HSBC');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '409', 'Unibanco');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '412', 'Banco Capital');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '422', 'Banco Safra');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '453', 'Banco Rural');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '456', 'Banco Tokyo Mitsubishi UFJ');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '464', 'Banco Sumitomo Mitsui Brasileiro');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '477', 'Citibank');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '479', 'Itaubank (antigo Bank Boston)');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '487', 'Deutsche Bank');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '488', 'Banco Morgan Guaranty');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '492', 'Banco NMB Postbank');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '494', 'Banco la República Oriental del Uruguay');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '495', 'Banco La Provincia de Buenos Aires');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '505', 'Banco Credit Suisse');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '600', 'Banco Luso Brasileiro');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '604', 'Banco Industrial');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '610', 'Banco VR');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '611', 'Banco Paulista');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '612', 'Banco Guanabara');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '613', 'Banco Pecunia');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '623', 'Banco Panamericano');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '626', 'Banco Ficsa');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '630', 'Banco Intercap');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '633', 'Banco Rendimento');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '634', 'Banco Triângulo');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '637', 'Banco Sofisa');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '638', 'Banco Prosper');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '643', 'Banco Pine');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '652', 'Itaú Holding Financeira');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '653', 'Banco Indusval');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '654', 'Banco A.J. Renner');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '655', 'Banco Votorantim');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '707', 'Banco Daycoval');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '719', 'Banif');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '721', 'Banco Credibel');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '734', 'Banco Gerdau');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '735', 'Banco Pottencial');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '738', 'Banco Morada');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '739', 'Banco Galvão de Negócios');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '740', 'Banco Barclays');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '741', 'BRP');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '743', 'Banco Semear');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '745', 'Banco Citibank');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '746', 'Banco Modal');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '747', 'Banco Rabobank International');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '748', 'Banco Cooperativo Sicredi');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '749', 'Banco Simples');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '751', 'Dresdner Bank');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '752', 'BNP Paribas');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '753', 'Banco Comercial Uruguai');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '755', 'Banco Merrill Lynch');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '756', 'Banco Cooperativo do Brasil');
INSERT INTO `BANCOS` (`ID`, `COD`, `NOME`) VALUES (NULL, '757', 'KEB');
